export const LAB_REALTIME_EVENT_TYPE = {
    ENVIRONMENT_CHANGED: 'ENVIRONMENT_CHANGED',
    TOPIC_CHANGED: 'TOPIC_CHANGED',
    CONSUMER_CHANGED: 'CONSUMER_CHANGED',
    PRODUCER_CHANGED: 'PRODUCER_CHANGED'
};

export const LAB_REALTIME_ACTION = {
    CREATED: 'CREATED',
    STARTED: 'STARTED',
    STOPPED: 'STOPPED',
    DELETED: 'DELETED',
    SENT: 'SENT'
};

export const ENVIRONMENT_STATUS = {
    CREATED: 'CREATED',
    RUNNING: 'RUNNING',
    START_FAILED: 'START_FAILED',
    STOPPED: 'STOPPED',
    STOP_FAILED: 'STOP_FAILED'
};
