export const LAB_REALTIME_EVENT_TYPE = {
    ENVIRONMENT_CHANGED: 'ENVIRONMENT_CHANGED',
    TOPIC_CHANGED: 'TOPIC_CHANGED',
    CONSUMER_CHANGED: 'CONSUMER_CHANGED',
    PRODUCER_CHANGED: 'PRODUCER_CHANGED',
    ACTIVITY_LOG: 'ACTIVITY_LOG',
    ACTIVITY_LOG_SNAPSHOT: 'ACTIVITY_LOG_SNAPSHOT',
    PRODUCER_MESSAGE: 'PRODUCER_MESSAGE',
    CONSUMER_MESSAGE: 'CONSUMER_MESSAGE',
    CONSUMER_RECV: 'CONSUMER_RECV',
    TOPOLOGY_SNAPSHOT: 'TOPOLOGY_SNAPSHOT',
    PRODUCER_SEND: 'PRODUCER_SEND'
};

export const TOPOLOGY_EVENT_TYPE = {
    TOPOLOGY_SNAPSHOT: LAB_REALTIME_EVENT_TYPE.TOPOLOGY_SNAPSHOT,
    PRODUCER_SEND: LAB_REALTIME_EVENT_TYPE.PRODUCER_SEND,
    CONSUMER_RECV: LAB_REALTIME_EVENT_TYPE.CONSUMER_RECV
};

export const LAB_REALTIME_ACTION = {
    CREATED: 'CREATED',
    UPDATED: 'UPDATED',
    STARTED: 'STARTED',
    STOPPED: 'STOPPED',
    DELETED: 'DELETED',
    SENT: 'SENT'
};

export const ENVIRONMENT_STATUS = {
    CREATED: 'CREATED',
    RUNNING: 'RUNNING',
    START_FAILED: 'START_FAILED',
    STOPPED: 'STOPPED',
    STOP_FAILED: 'STOP_FAILED'
};
